# Generated by Django 4.1.4 on 2022-12-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='order_status',
            field=models.CharField(choices=[('PD', 'pendenting'), ('DN', 'done')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
