# Generated by Django 4.1.4 on 2022-12-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_itemorder_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
    ]
